apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgDTAObp3o6pOeLA5KBqrBVB7pmvR7JSiq7uAvRWrGGwyYFEWO+82I+BMOQan6c9dHKpvXeuyHIcdWcAqYbYabAXLZNf6lckrVOu02YR+1hSEuF08hnDzy8KoLp1CwKFVgLX2yP4HrIxx6mrPjLYrlD6qkHlnteQSfGGoTFzro0EE/MZy/BoW+MlZagiF/e3sgMZ0Ij3aKajpFWEiYcupsiD6+33sSJDU8FIrDcJIVAJ8rjE48BL3DQ/aDPrcONLhfI4NhVrXVuY6H0vonLzc/xGBbGvh8nG9/nxhb86gwUwl7fzCbwm/+fR37XQvBiT82P20TDeoDDqiWEmJWdtN4wpzpOBfmIQ2W3iqOa1UL3vG448GJk5Uq19Ac2TZa4+XBbxQwKERIYKt4drTrOhuBZV8ezn+G7bUTp6HLgKPkhI3hHLKt95fzPDHKQ0TVfLIy2ozmh2Y/Ukzsb2RIbOWmMhCd0xykiff04PwntMIDkDV31Imiq5FjaWxl2N/X1Uej5/9ukeWUmDWpMIt3g/unZtQVXxhmxqaIPmEKYgaAeNNyL2rDyNsGK/FpBBW/rmXi2Kf3uFJYggDvtuA7LBBeVtiSAeNGY2Lq0RXKWAV9JxdNpWDAm5UiwHvsGIhlGgrCFaciZ3RaVN54afgg0NPE6KVB9HYgecxCYtd4Om4UfklOTjnaXCjUZjgsxSFesgpmjIxm0u8iULACYmbO/W2+qXH7ZW6zvkWqyyyI7215B5lHK0mFkaKHwDGhisW1jLttdy8WBYn4vlmGi6nEIC40wRdBCrMQgydF4aWEetw6qIoNCzIEvnyjJa7f2ew/b5TEZPEjyiFYcjRQLQtc0x8fBo/hgg+EMUmM0wxish0PjncuOGgd1gAfURxnrKWGKzt3zf/Yo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

