apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB2UfCd9UTa+p3DVUn7XxbgyN0jYFQvXIWmgKPfJ+5r6TM9YyuXUB5TE2E7S6wsPfwE15BXEpeemmceKWyeKBabBlmWB8B+NrHKdWfLmS/QjUyTiTWZwJgWWxq2dEN1ZFVdr6/v13q2Sg54BUdNIgxYMOFyjK1KZU09SN7cEggLc94uXd4pWxCeanBTs14/9vJa4Dw2x9TRwWyhfBo13WEgWDnrSwCnfdkPlJsDSmmi5NSxNus8kzbfIsG1KAw+aldCAKOVTjPSzLJklKC8wg3ZjKhTicEfr4Oi7GSjWWIqRjYrlANfkjORWysHjVAT1gRecEhByNg/+ih0sv+jazl0lkHzCpwyrTh+u8YX0AhVLwQUcAeIxfLX/Ct2RbWPeAbr3FltAmAIVqRr5PtcBlvdD4cZnl8FGAw+J8H5dNJWFZ/HBoYqjMv5GJq6sgVYZH+NFoJHi7WTWYFluxNS9jveiLyYxeHlpsd5bvTZa9KFIwRVAVOTkWLqPzskQw3BbedbfjYoHk/FeEoT7JJw2YOo64SvUsnyb41CDp2BU4aB2EVkFGc3EiHZpYjOwv6QkFK5SZX2yhc3T8RMMh2shiw+0sIbxAkzEwSZUTl0Hw14AUY6VnJRfU3TNRn01hk7RGvvzcun9ekOkWCW0Y53NQd2MegEvNIUU4O2JjGKAhjT9vjofwmEYE3A92vmqC1qAlFI2rqXwL8FyutoEob3MVNODwp+ZzcBSmesC0oXDHRb/fmFTTepF4kXkwiqsS0XRyG9l4avewLh3aYJXRMjxqsVeg3Gyfx38DnsoqObj+NbxDwhDHIPjI3DRC8p/LNkqTlsrIW3omAmBNlHrKfc0Sm/N/+NHi2l2In4ofrACqcNmKlntx+eItS7F5gPVyQvJf4cTZI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

