apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBtthy6yCDurhCDpro3D24XJ5u2dCUQRwEXV5309TXvZCFwoZU23Ygc+S3rsEu27P/2l6QIZsFYtAfGSAGhtfJ7FyyneLaju2/On6gJ81e4igC+Pfgwbt1+FukLXfMYgrapyeQ2C6KI0gqdrxcN2QFPQSFFpfhHeC+gmdRQAwb5pa07ut5owlgTOeB7Be8BX1Xa3OHbxM5OcPFyBesnKPKJGjUOSVpUUC7K86i+O4J/eRTi/0tCS1MKARXkWFMRfhQaH75BJqszoKKKZKXCBf6lKC79XRz2MgFkqHEUhk97uiuGfL7o1p4a7hK3HgljqlwTru9S2AScMUhFkYz3C1IpNASjRUoJAAtkWgTiVOOCMVntvAzHWl7qQC1qpBXw98HgoAwP19hsQ00dwGIVW+Oxht7yjgtmLrnW7QdB6aCuFL7OdA+t9FnaKy/g8sMkH3CQK8dpKlo5KhE1pLn5LDGI7tSJgh6ZrUSKjBJewm8UMJGbrwUUyRBDi6py4BiTE61uBhowwhWR5EzaPHMxh7jSY0nOgf+MSEGB5L4hFpAQuNNruJEqDPaFAJlCOt1M5RVrBabQzlSJ9UX3y+V+ZlPwvfKQ+Je8O8CdwCWNviUqfPYtC3dE9YZBp+LZ7GkcUx9MeNrRIGeEhHs/EEJGmXc4a2akwuBOLhBDPG+dLJznABpCh1+UEAkKTUD2PQOL1SwA89puJ2WRS4g9sJhauPtybBRvrdzbJsS0pLyZwJvEw0QhJGOZ2oX3prxcNuYjhjTrFMNTTZTqGdPhxBTaNQy28vQ1L1ASohwvtkOXHUVo67kaMGWj0apJ1T1w0L6XlAGypAbE2CX3E2/WCggBZBuds0YfZONASHo01XjHMdlYwnVHsVoWCWt5y2EZ+EE21ddmrRQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

