apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAwCQLZM6C+NKW2uqlbimh/xrUoG4+8XrM4mXQ9O3mfF/yAH1j/eJSxjYRUn/TFPWXjZjpTSFtbRikrOi6bOJcO+MZoltbU1ShEsAGLjRdbTdFe+zxJwqDM53kE2ZpGy6x17z+xaUGSIrbhNc/kGcdTVo3OiU0EV0kpbccrD6OQXigfBb3xdtVXEes/WmXttMwgIAratqDv3mRJJmhFbbdZqYWjVQ4c8Qa8Fwoosglo37NdPUQlkkCLC5J7E3O631jrGpp4cNEA2f2dxs7LzN1T4T3g9KaQAbhV8xY/yAwehWWQXPqyCN8vJsyoKZ7nxyE45LEltJC2kHHpRVZjhY0jFsNq/OgP8JKbo+ySvOvlxbmIiqCLuDUex67TQD8Nw8eEivoZ0JrNQXyUIR5tciYHIkHimD9Td0AoWbDhfZhosZwHr2cvibDP/zliQ0MColtUH5ftADV5+ar7/vbS4jtFNM7VdwCTajNKRQtN19RLWGywP5VhrRLd0b1AqVzva0MS2/vRSk0d0WWvdqBDuFem+XAfLzDMCTXliqVrCzoyaRrINEsDkNKpmOSjL+RLmd0XCtiQPAyvPEUKl/K5QgdVgAoUbMj1JBX+rksiAkpONp9a8s9LF+OrCLEYJoqcj0sWctZEkSuSyIpUbrNv2oqV8GXKyofpSfLfAkfZJfxN1khof9k/sdHorSiEjCxxs1vgJbAXUtbEM1pdn7VYVqe/Kk24aPxm+nvUydJcfY9gJec5p5LlhzP4Nw0fQCvubtLA08MqDiTvnS4nHL1MgaYwC1HOzJmtLohV1E9N/Rx5hH+yQ1Zl94/TKQ8xgsN7T0nHxC/rIB6gWUcZfLK6qv2A6sVEby1mq6Eps/CyzXGKaIxWoZ+m2xUFMUVNJQWDWMK6yaE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

