apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCbQ8FtLPS6aakZjFv+Ag0q/LsKaKaqTTQZri3SzwMW59K/CzuBVukO1838gmFkgMZOJXpZOneWo2+zKPtm1QvhVhYLnDRNItdGjgyM33AnWqLZABOjhG8wK6Dl3JgKYY6ybjL9DeJQX8cNuECStwnahoh3gONKxC7pujA3TbNOfA4H271F97miEQJF0yqpyh2I2RPN7rWrUJvRWu+2RwpgzwUK3vJpy2F6UkmVnvZ8d0BfEdn1yV3zJCekaytnMal5XJNYTQk5ytibhPkVpur0UgFR9m2WhEBh/RSMpcnKEeruevx45za+ZJpi8esuHndZCEjF1GFE+RG0RaEz0PH97f7mwuN1bet0XVE/GCYK4A+4aWc3aYDDaOfPl6HTeBLRBlzSdMf8fGELNewWvQphK1/drKD0LShjIfAh2Z8rW1M+H7slmm51L4UWzXJEiLpOUy28abwRoJmAi8PJBiEAUZYdCnaaxGWKyNZHP/Wv5LWeO3s99rBAKijxE9ArYwEHV4P+ZaPppF6C1WUJTLAf7tCPSylkmdH6DTF0Ce3aixYQqJybipWQvMsnAQnjXDOovwcmBotQ2qkVl9WlBvEiozubkK02NDt6xcLYeqmnjNw9Q6uFIZ+NhUXyhcT3cIBc3JyWw5KZ3mqvx8LVjxO8B9WM7S0xUUzmSeGVOTRNOGN58/RGshPH4vUybMb9m06XgrP81pwWWsVkQ/vMimromy3V6J3rT3xeGftNQZDs5OemYW0Xc5/jplAn6GanH9beOAdNNmcmZNBkbpejLBjP7zH24MJO2BBuTD/aaogTDu/2dyNxgEZew6zOHZq8shRiDXaqEgjGd15byv85xya7TDusEd/r8unM5lY/cH175k3CopUUVpjQobZC+I8+WNr3b88=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

