apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA2i63sb2B05Gaq4Ry6YC1PpTEzL8hVqZi3yDUGoHXSqsdvhG+sNr6HSnSkzfbV64MafHj6tWXRZ85uGIo/g6biqSfdeusvMbuWyQDqFrvY9OEdAWt7VqK4o6zD7BVpefXesK3g8Kd7Zb51eaK9E03y5Nyg4MKbCY1WOzS8u7WgOFD0HTNVkBm7EJ444iumwPICGXRhxJHdnUKzktXmInitg8MURKIASYyg/w5zZ1oOCkYMtWpBygI3blUgWQBesE3tYKixCLhcqQykmqmhI3SOdleiy4lWD3PvxneGyFRfKPFCymBEwjXBQpjPG7D+zmY59dkllU0pMyjiPE+sZ5xzwVslJrwoFo2PCtJLjlF0lfHGTKSbDv40i8TfU2+wni2En8W0jzVnANJJYky7rK81fMDxa6+RiZWZPcm3xY1PIyiN6dgMbr3SjO+CsM7gnor4Csh5wQd7hb+yL9zMQBOtt0Hk2n7U06aeqTMUd5Np9LcAEwzmBBFPSHw8i1aPbtw07h9lVkXrlbx4zjWh0ZbN6jLdbYYrt4y07Lj5nzCSEYd8TokrEkZHBzaWj5FjqQsYHPN3Z9yYksNcou+z79APaH1EO+bvFIPZnW92126HM+PVM06zInnpcVw408KLqSRt+KOQ6hx7uqhLIx6Or7V6gCdRUUiPshHQtgI0Sax3EB+JMrUvBsiNgtHUrhvJCIqLdJQrJzJqASjXrxsqYU5x+50z3sl43kFb9Je3/ZSqVh9LXjDiQUrTGiGO5tGlLTY6pVIJ/EOz9rz2oh71WWTUVv1AaFSYbesht7npvKpPtkNAe2QuIJfU1jdZtQ7neiPeamkrTRJLmWgcdf+BcOs1NKLDCjB6DdVewS1g4yTSelnp+t+2vLpOD8hwJIWxY8g3udg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

