apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAD3MihqmStyyyDotrdoUO99Y5xjHYWzFndW02zHcPBuvc6UQTn4vyznc0LGFm0hGcNzR4Bmm4yNhhHJT5ABaezlP3j9qErMrDsU4FlgfrGQBjLN+5ybLdFlLUM1CmzXWPcLRGauCXHbOuttc8bvnGi1vcd5dp88/Qzz0sBaYaXr+7d7w59n1ni//TYQYMBTS9H3L1ErCuhLNCxQnXrNFht7onMBFY79X+wu75id80fTMMu59fQLiehdHYBH7rs6W3DdFa+IndO4HSEgbFkO8Gs0J6MKoivF3OP+bfANtkPb4upytkGIatYSltpu748gTmeqgFL1uo7WWoBRwGWMUZn2CKFfXkpA6r/9g/NA0quzNH0fdPr9dlFoz3rIqUeECF88ZQlWLk0MuwJ8Xb+oEDYw9UVB5OHbMGimUHFGNhSz12PJ0nFlezwH3IB7cnXFVyBPoipa5YU12yKtbRMvQCynm9aSW19Y65cYfE17kqNf2rX3CBq7KDil8OyDER0B/Bl0lO7fxtrLx6nS6/PjII8ugGoLeCCWXz16cgGwpM1JC6IT7SnrQrohlzFYk3g9xvOx2digPtKRBchC3WiZf+TRHvJo/3wLaJ3DFfQ068ESSdhDGtxWG7aj9AA17ynUa5PsruaTijUYaQTLvCflYBwcReQwEelpLzJkc7V7dz49WEwIPXGrSPfTxZGcnnJIaNNbNrPAjFCALR2OzknlYAn/EPImtBihs21EzmgbvrQFXV+uo9hWJ8WAjq1m8nNMpwnigJCetHRtW9QZrytf6DpYei5fVikLSnQxRcrIpLq9gc4BDBJrGI78qeMfGi0uOorAe+pNxiVG97HWSfAa3d7InEKAycOm7so0Lrp0pFQpUVWE3wh/mG6HLpw9YYwmdQU7Ek=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

